"""The readable results doc, generated from results.json only (S0 spec §5.7)."""
from __future__ import annotations

from v2.probes.registry import PROBES
from v2.probes.results import ResultsStore

ANCHOR_ROWS = 5


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def render_report(store: ResultsStore, generated_on: str) -> str:
    env = store.environment
    lines = [
        f"# S0 probe results — {generated_on}",
        "",
        "> Generated by `python -m v2.probes report` from `v2/probes/results/results.json`. Don't edit by hand:",
        "> design consequences go into the Part 1 spec, status into the tracker.",
        "",
        "## Environment",
        "",
        "| Item | Value |",
        "|---|---|",
    ]
    for key in ("wine", "tally_version", "edition", "licence", "run_mode"):
        lines.append(f"| {key} | {_cell(str(env.get(key, '—')))} |")
    lines += ["", "## Results", "", "| Probe | Name | Companies | Outcome | Summary | Design impact |",
              "|---|---|---|---|---|---|"]
    for item in PROBES:
        if item.deferred:
            continue
        entry = store.probe_entry(item.id)
        if entry is None:
            lines.append(f"| {item.id} | {item.name} | {item.companies} | not run | — | — |")
            continue
        parts = sorted(entry["parts"].items())
        summary = "; ".join(f"{label}: {part['summary']}" for label, part in parts)
        impact = "; ".join(f"{label}: {part['spec_impact']}" for label, part in parts if part["spec_impact"])
        remaining = entry.get("remaining") or []
        outcome = f"PARTIAL (remaining: {', '.join(remaining)})" if entry["outcome"] == "PARTIAL" and remaining \
            else entry["outcome"]
        lines.append(f"| {item.id} | {item.name} | {item.companies} | {outcome} | {_cell(summary)} | "
                     f"{_cell(impact) or '—'} |")
    lines += ["", "## Company A anchors checks", ""]
    checks = store.anchor_checks[-ANCHOR_ROWS:]
    if not checks:
        lines.append("No anchors check has run yet.")
    else:
        lines += ["| Ran at | When | Result | Problems |", "|---|---|---|---|"]
        for check in checks:
            problems = _cell("; ".join(check["problems"])) or "—"
            lines.append(f"| {check['ran_at']} | {check['when']} | {'OK' if check['ok'] else 'FAILED'} | {problems} |")
    lines += ["", "## Deferred (tier C, Q29)", ""]
    lines += [f"- Probe {item.id} — {item.name}" for item in PROBES if item.deferred]
    lines.append("- Probe 21's timing half, and the standard-edition runs of probes 7 and 13")
    return "\n".join(lines) + "\n"
